#!/usr/bin/env node
/**
 * Generate THIRD-PARTY-NOTICES.txt for the packaged desktop app.
 *
 * Walks the desktop app's *production* dependency closure (via `npm ls`)
 * and emits each third-party package's name, version, SPDX license, and
 * bundled license text. First-party `@otelux/*` packages are covered by
 * the repository LICENSE and are skipped. Electron ships its own Chromium
 * and Electron notices inside the packaged app, so they are not repeated
 * here.
 *
 * Run from anywhere; output is written to `apps/desktop/build/THIRD-PARTY-NOTICES.txt`.
 * Regenerate whenever the desktop's runtime dependencies change.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const desktopDir = join(here, '..');
const repoRoot = join(desktopDir, '..', '..');
const outFile = join(desktopDir, 'build', 'THIRD-PARTY-NOTICES.txt');

const LICENSE_FILE_NAMES = /^(LICENSE|LICENCE|COPYING|NOTICE)(\..*)?$/i;

/** Collect unique third-party `name` -> version from the npm ls tree. */
function collect(node, into) {
	for (const [name, dep] of Object.entries(node.dependencies ?? {})) {
		if (!name.startsWith('@otelux/') && dep.version) {
			into.set(name, dep.version);
		}
		collect(dep, into);
	}
}

// Dependencies are hoisted to the repo-root `node_modules`. Resolve the
// package directory by path instead of `require.resolve`, which many
// packages block for `./package.json` via their `exports` map.
function packageDir(name) {
	const dir = join(repoRoot, 'node_modules', name);
	return existsSync(join(dir, 'package.json')) ? dir : undefined;
}

function readLicenseText(pkgDir) {
	let entries;
	try {
		entries = readdirSync(pkgDir);
	} catch {
		return undefined;
	}
	const file = entries.find((e) => LICENSE_FILE_NAMES.test(e));
	if (file === undefined) {
		return undefined;
	}
	try {
		return readFileSync(join(pkgDir, file), 'utf8').trim();
	} catch {
		return undefined;
	}
}

function licenseId(pkgJson) {
	if (typeof pkgJson.license === 'string') {
		return pkgJson.license;
	}
	if (typeof pkgJson.license === 'object' && pkgJson.license?.type) {
		return pkgJson.license.type;
	}
	return 'UNKNOWN';
}

const raw = execFileSync('npm', ['ls', '-w', '@otelux/desktop', '--omit=dev', '--all', '--json'], {
	cwd: repoRoot,
	encoding: 'utf8',
	maxBuffer: 64 * 1024 * 1024,
});
const names = new Map();
collect(JSON.parse(raw), names);

const sorted = [...names.keys()].sort((a, b) => a.localeCompare(b));

const blocks = sorted.map((name) => {
	const version = names.get(name);
	const dir = packageDir(name);
	let pkgJson = {};
	if (dir !== undefined) {
		try {
			pkgJson = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
		} catch {
			// Leave pkgJson empty; header still reports name@version.
		}
	}
	const id = licenseId(pkgJson);
	const homepage = pkgJson.homepage ?? pkgJson.repository?.url ?? pkgJson.repository ?? '';
	const text = dir !== undefined ? readLicenseText(dir) : undefined;
	const header = `${name}@${version}  (${id})${homepage ? `\n${homepage}` : ''}`;
	const body = text ?? `License: ${id} (no bundled license file found).`;
	return `${header}\n\n${body}`;
});

const preamble = `OTelux Desktop — Third-Party Notices

This file lists third-party packages bundled with the OTelux desktop app
and their licenses. First-party @otelux/* packages are covered by the
repository LICENSE. Electron bundles and ships its own Chromium and
Electron license notices within the packaged application.

Generated by scripts/generate-notices.mjs from the production dependency
closure. Regenerate when runtime dependencies change.

Packages: ${sorted.length}
`;

writeFileSync(
	outFile,
	`${preamble}\n${'='.repeat(72)}\n\n${blocks.join(`\n\n${'-'.repeat(72)}\n\n`)}\n`,
);
console.log(`Wrote ${outFile} (${sorted.length} packages).`);
